runtime: node42
build: npm install && bower install && grunt
run: node examples/basic run
test: |
  if [[ -n "$ROCK_ARG1" ]];then
    node node_modules/.bin/nodeunit "tests/${ROCK_ARG1}"
  else
    node node_modules/.bin/nodeunit tests
  fi

run_test_server: rm -f /var/tmp/showcase-test.sqlite ; node examples/basic schema-sync ; node examples/basic fixtures-sync ; PORT=9800 node examples/basic run
