runtime: node010
build: npm install && bower install && grunt
run: gnode examples/basic run
test: |
  if [[ -n "$ROCK_ARG1" ]];then
    gnode node_modules/.bin/nodeunit "tests/${ROCK_ARG1}"
  else
    gnode node_modules/.bin/nodeunit tests
  fi

run_test_server: rm -f /var/tmp/showcase-test.sqlite ; gnode examples/basic schema-sync ; gnode examples/basic fixtures-sync ; PORT=9800 gnode examples/basic run
